---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      host: swarm-test.autonomic.zone
      stack: ${REPO_NAME_KEBAB}
      purge: true
      deploy_key:
        from_secret: drone_ssh_swarm_test
    environment:
      DOMAIN: ${REPO_NAME_KEBAB}.swarm-test.autonomic.zone
      STACK_NAME: ${REPO_NAME_KEBAB}
      LETS_ENCRYPT_ENV: production
trigger:
  branch:
    - main
