---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      host: swarm-test.autonomic.zone
      stack: ${REPO_NAME_SNAKE}
      purge: true
      deploy_key:
        from_secret: drone_ssh_swarm_test
    environment:
      DOMAIN: ${REPO_NAME_KEBAB}.swarm-test.autonomic.zone
      STACK_NAME: ${REPO_NAME_SNAKE}
      LETS_ENCRYPT_ENV: production

  - name: notify coopcloud-dev on failure
    image: plugins/matrix
    settings:
      homeserver: https://matrix.autonomic.zone
      roomid: "IFazIpLtxiScqbHqoa:autonomic.zone"
      userid: "@autono-bot:autonomic.zone"
      accesstoken:
        from_secret: autono_bot_access_token
    depends_on:
    - deployment
  when:
    status:
      - failure
trigger:
  branch:
    - main

---
kind: pipeline
name: recipe release
steps:
  - name: release a new version
    image: yashodhank/inlets:latest
    settings:
      command: recipe ${REPO_NAME} release
      deploy_key:
        from_secret: abra_bot_deploy_key

  - name: trigger downstream builds
    image: plugins/downstream
    settings:
      server: https://drone.autonomic.zone
      token:
        from_secret: decentral1se_token
      fork: true
      repositories:
        - coop-cloud/auto-apps-json
    depends_on:
      - release a new version