---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      host: swarm-test.autonomic.zone
      stack: ${REPO_NAME_SNAKE}
      purge: true
      deploy_key:
        from_secret: drone_ssh_swarm_test
    environment:
      DOMAIN: ${REPO_NAME_KEBAB}.swarm-test.autonomic.zone
      STACK_NAME: ${REPO_NAME_SNAKE}
      LETS_ENCRYPT_ENV: production
trigger:
  branch:
    - main

---
kind: pipeline
name: recipe release
steps:
  - name: release a new version
    image: decentral1se/drone-abra:latest
    settings:
      command: recipe ${REPO_NAME_TITLE} release
      deploy_key:
        from_secret: abra_bot_deploy_key
trigger:
  event:
    - tag