---
version: "3.8"

services:
  inlets:
    image: dezsh/inlets:amd64
    container_name: ${TYPE}
    hostname: ${DOMAIN}
    entrypoint: ["inlets"]
    environment:
     - INLETS_TYPE
     - INLETS_PORT
    command:
      - "${INLETS_TYPE}"
      - "--port=${INLETS_PORT}"
      - "--token=${cat /run/secrets/inlets_shared_token}"
    secrets:
      - inlets_shared_token
    networks:
      - proxy
    deploy:
      update_config:
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${DOMAIN}`) || HostRegexp(`{subdomain:[a-z1-9-]+}.${DOMAIN}`)"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=web-secure"
        - "traefik.http.routers.${STACK_NAME}.tls.certresolver=${LETS_ENCRYPT_ENV}"
        - "traefik.tcp.routers.${STACK_NAME}-intcp.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.${STACK_NAME}-intcp.entrypoints=inlets-intcp"
        - "traefik.tcp.services.${STACK_NAME}-intcp.loadbalancer.server.port=${INLETS_PORT}"
        - "traefik.http.services.${STACK_NAME}-intcp.loadbalancer.server.port=${INLETS_PORT}"
        - "traefik.http.routers.${STACK_NAME}.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.${STACK_NAME}.tls.domains[0].sans=*.${DOMAIN}"
        - "coop-cloud.${STACK_NAME}.app.version=3.0.2"

networks:
  proxy:
    external: true
secrets:
  inlets_shared_token:
    name: ${STACK_NAME}_inlets_shared_token_${SECRET_INLETS_SHARED_TOKEN_VERSION}
    external: true
